SET ECHO ON

REM
REM 7. Displaying Data from Multiple Tables
REM
REM Setup
REM


REM
REM CREATE TABLE PORTS
REM

DROP   TABLE PORTS;
CREATE TABLE PORTS
(  PORT_ID             NUMBER
 , PORT_NAME           VARCHAR2(20)
 , COUNTRY             VARCHAR2(40)
 , CAPACITY            NUMBER
 , CONSTRAINT          PK_PORT 
                       PRIMARY KEY (PORT_ID)
);

REM
REM CREATE TABLE SHIPS

REM

DROP   TABLE SHIPS;
CREATE TABLE SHIPS
(  SHIP_ID             NUMBER(7)
 , SHIP_NAME           VARCHAR2(20)
 , CAPACITY            NUMBER
 , LENGTH              NUMBER
 , HOME_PORT_ID        NUMBER
 , CONSTRAINT          PK_SHIP 
                       PRIMARY KEY (SHIP_ID)
);

REM
REM CREATE TABLE EMPLOYEES
REM

DROP   TABLE EMPLOYEES;
CREATE TABLE EMPLOYEES
(  EMPLOYEE_ID         NUMBER(7)
 , SHIP_ID             NUMBER(7)
 , FIRST_NAME          VARCHAR2(20)
 , LAST_NAME           VARCHAR2(30)
 , POSITION_ID         NUMBER
 , SSN                 VARCHAR2(11)
 , DOB                 DATE
 , PRIMARY_PHONE       VARCHAR2(20)
 , CONSTRAINT          PK_EMPLOYEES 
                       PRIMARY KEY (EMPLOYEE_ID)
); 

REM
REM CREATE TABLE VENDORS
REM

DROP   TABLE VENDORS;
CREATE TABLE VENDORS
(  VENDOR_ID           NUMBER
 , VENDOR_NAME         VARCHAR2(20)
 , CONSTRAINT          PK_VENDOR_ID
                       PRIMARY KEY (VENDOR_ID)
);

REM
REM CREATE TABLE ADDRESSES
REM

DROP   TABLE ADDRESSES;
CREATE TABLE ADDRESSES
(
   ADDRESS_ID          NUMBER
 , EMPLOYEE_ID         NUMBER
 , STREET_ADDRESS      VARCHAR2(40)
 , STREET_ADDRESS2     VARCHAR2(40)
 , CITY                VARCHAR2(30)
 , STATE               VARCHAR2(2)
 , ZIP                 VARCHAR2(5)
 , ZIP_PLUS            VARCHAR2(4)
 , COUNTRY             VARCHAR2(20)
 , CONTACT_EMAIL       VARCHAR2(80)
 , CONSTRAINT          PK_ADDRESS_ID
                       PRIMARY KEY (ADDRESS_ID)
);

REM
REM CREATE TABLE SHIP_CABINS
REM

DROP   TABLE SHIP_CABINS;
CREATE TABLE SHIP_CABINS
(  SHIP_CABIN_ID       NUMBER
 , SHIP_ID             NUMBER(7)
 , ROOM_NUMBER         VARCHAR2(5)
 , ROOM_STYLE          VARCHAR2(10)
 , ROOM_TYPE           VARCHAR2(20)
 , WINDOW              VARCHAR2(10)
 , GUESTS              NUMBER(3)
 , SQ_FT               NUMBER(6)
 , BALCONY_SQ_FT       NUMBER(6)
 , CONSTRAINT          PK_SHIP_CABIN_ID 
                       PRIMARY KEY (SHIP_CABIN_ID)
 , CONSTRAINT          CK_WINDOW 
                       CHECK (WINDOW IN ('Ocean',
                              'Balcony', 'None'))
);

REM
REM CREATE TABLE ONLINE_SUBSCRIBERS
REM

DROP   TABLE ONLINE_SUBSCRIBERS;
CREATE TABLE ONLINE_SUBSCRIBERS
(
   ONLINE_SUBSCRIBER_ID NUMBER
 , LASTNAME             VARCHAR2(30)
, CONSTRAINT           PK_ONLINE_SUBSCRIBER_ID
                        PRIMARY KEY (ONLINE_SUBSCRIBER_ID)
);

REM
REM CREATE TABLE POSITIONS 
REM

DROP   TABLE POSITIONS;
CREATE TABLE POSITIONS
(  POSITION_ID         NUMBER(4)
 , POSITION            VARCHAR2(20)
 , REPORTS_TO          NUMBER
 , EXEMPT              CHAR(1)
 , MIN_SALARY          NUMBER(10,2)
 , MAX_SALARY          NUMBER(10,2)
 , CONSTRAINT          PK_POSITIONS 
                       PRIMARY KEY (POSITION_ID)
);

REM
REM CREATE SEQUENCE SEQ_SHIP_ID
REM

DROP   SEQUENCE SEQ_SHIP_ID;
CREATE SEQUENCE SEQ_SHIP_ID;

REM
REM CREATE SEQUENCE SEQ_PORT_ID
REM

DROP   SEQUENCE SEQ_PORT_ID;
CREATE SEQUENCE SEQ_PORT_ID;

REM
REM CREATE SEQUENCE SEQ_EMPLOYEE_ID
REM

DROP   SEQUENCE SEQ_EMPLOYEE_ID;
CREATE SEQUENCE SEQ_EMPLOYEE_ID;

REM
REM CREATE SEQUENCE SEQ_ADDRESS_ID 
REM

DROP   SEQUENCE SEQ_ADDRESS_ID;
CREATE SEQUENCE SEQ_ADDRESS_ID;

REM
REM CREATE SEQUENCE SEQ_SHIP_CABIN_ID
REM

DROP   SEQUENCE SEQ_SHIP_CABIN_ID;
CREATE SEQUENCE SEQ_SHIP_CABIN_ID;

REM
REM CREATE SEQUENCE SEQ_POSITION_ID
REM

DROP   SEQUENCE SEQ_POSITION_ID;
CREATE SEQUENCE SEQ_POSITION_ID;

REM
REM CREATE SEQUENCE SEQ_VENDOR_ID
REM

DROP   SEQUENCE SEQ_VENDOR_ID;
CREATE SEQUENCE SEQ_VENDOR_ID;

REM
REM CREATE SEQUENCE SEQ_ONLINE_SUBSCRIBER_ID
REM

DROP   SEQUENCE SEQ_ONLINE_SUBSCRIBER_ID;
CREATE SEQUENCE SEQ_ONLINE_SUBSCRIBER_ID;

REM
REM INSERT INTO POSITIONS
REM

INSERT INTO POSITIONS 
  (  POSITION_ID, POSITION, MAX_SALARY)
VALUES
  (  SEQ_POSITION_ID.NEXTVAL, 'Captain', 240000);

INSERT INTO POSITIONS 
  (  POSITION_ID, POSITION, REPORTS_TO, MAX_SALARY)
VALUES
  (  SEQ_POSITION_ID.NEXTVAL, 'Director', 1, 175000);

INSERT INTO POSITIONS 
  (  POSITION_ID, POSITION, REPORTS_TO, MAX_SALARY)
VALUES
  (  SEQ_POSITION_ID.NEXTVAL, 'Manager', 2, 120000);

INSERT INTO POSITIONS 
  (  POSITION_ID, POSITION, REPORTS_TO, MAX_SALARY)
VALUES
  (  SEQ_POSITION_ID.NEXTVAL, 'Crew Chief', 2, 88300);

INSERT INTO POSITIONS 
  (  POSITION_ID, POSITION, REPORTS_TO, MAX_SALARY)
VALUES
  (  SEQ_POSITION_ID.NEXTVAL, 'Crew', 4, 65000);

REM
REM INSERT INTO PORTS
REM

INSERT INTO PORTS
(  PORT_ID, PORT_NAME, COUNTRY, CAPACITY)
VALUES
(  SEQ_PORT_ID.NEXTVAL
 , 'Baltimore', 'USA', 2)
;

INSERT INTO PORTS
(  PORT_ID, PORT_NAME, COUNTRY, CAPACITY)
VALUES
(  SEQ_PORT_ID.NEXTVAL
 , 'Charleston', 'USA', 2)
;

INSERT INTO PORTS
(  PORT_ID, PORT_NAME, COUNTRY, CAPACITY)
VALUES
(  SEQ_PORT_ID.NEXTVAL
 , 'Tampa', 'USA', 8)
;

INSERT INTO PORTS
(  PORT_ID, PORT_NAME, COUNTRY, CAPACITY)
VALUES
(  SEQ_PORT_ID.NEXTVAL
 , 'Miami', 'USA', 6)
;

INSERT INTO PORTS
(  PORT_ID, PORT_NAME, COUNTRY, CAPACITY)
VALUES
(  SEQ_PORT_ID.NEXTVAL
 , 'Galveston', 'USA', 6)
;


REM
REM INSERT INTO SHIPS
REM

INSERT INTO SHIPS
(  SHIP_ID, SHIP_NAME, CAPACITY, LENGTH, HOME_PORT_ID)
VALUES
(  SEQ_SHIP_ID.NEXTVAL
 , 'Codd Crystal', 2052, 855, 1) 
;

INSERT INTO SHIPS
(  SHIP_ID, SHIP_NAME, CAPACITY, LENGTH, HOME_PORT_ID)
VALUES
(  SEQ_SHIP_ID.NEXTVAL
 , 'Codd Elegance', 2974, 952, 3) 
;

INSERT INTO SHIPS
(  SHIP_ID, SHIP_NAME, CAPACITY, LENGTH, HOME_PORT_ID)
VALUES
(  SEQ_SHIP_ID.NEXTVAL
 , 'Codd Champion', 2974, 952, NULL) 
;

INSERT INTO SHIPS
(  SHIP_ID, SHIP_NAME, CAPACITY, LENGTH, HOME_PORT_ID)
VALUES
(  SEQ_SHIP_ID.NEXTVAL
 , 'Codd Victorious', 2974, 952, 3) 
;

INSERT INTO SHIPS
(  SHIP_ID, SHIP_NAME, CAPACITY, LENGTH, HOME_PORT_ID)
VALUES
(  SEQ_SHIP_ID.NEXTVAL
 , 'Codd Grandeur', 2446, 916, 2) 
;

REM INSERT INTO SHIPS
REM (  SHIP_ID, SHIP_NAME, CAPACITY, LENGTH, HOME_PORT_ID)
REM VALUES
REM (  SEQ_SHIP_ID.NEXTVAL
REM  , 'Codd Prince', 395, 470, 2) 
REM ;

REM
REM INSERT INTO SHIP_CABINS
REM

INSERT INTO SHIP_CABINS
  (  SHIP_CABIN_ID, SHIP_ID, ROOM_NUMBER, ROOM_STYLE , ROOM_TYPE ,  WINDOW, GUESTS, SQ_FT, BALCONY_SQ_FT)
VALUES               
  (  SEQ_SHIP_CABIN_ID.NEXTVAL
                  , 1      , 102        , 'Suite'    , 'Standard', 'Ocean',      4,   533, 139);

INSERT INTO SHIP_CABINS
  (  SHIP_CABIN_ID, SHIP_ID, ROOM_NUMBER, ROOM_STYLE , ROOM_TYPE ,  WINDOW, GUESTS, SQ_FT, BALCONY_SQ_FT)
VALUES               
  (  SEQ_SHIP_CABIN_ID.NEXTVAL
                  , 1      , 103        , 'Stateroom', 'Standard', 'Ocean',      2,   160, NULL);

INSERT INTO SHIP_CABINS
  (  SHIP_CABIN_ID, SHIP_ID, ROOM_NUMBER, ROOM_STYLE , ROOM_TYPE ,  WINDOW, GUESTS, SQ_FT, BALCONY_SQ_FT)
VALUES               
  (  SEQ_SHIP_CABIN_ID.NEXTVAL
                  , 1      , 104        , 'Suite'    , 'Standard', 'None' ,      4,   533, 139);

INSERT INTO SHIP_CABINS
  (  SHIP_CABIN_ID, SHIP_ID, ROOM_NUMBER, ROOM_STYLE , ROOM_TYPE ,  WINDOW, GUESTS, SQ_FT, BALCONY_SQ_FT)
VALUES               
  (  SEQ_SHIP_CABIN_ID.NEXTVAL
                  , 1      , 105        , 'Stateroom', 'Standard', 'Ocean',      3,   205, NULL);

INSERT INTO SHIP_CABINS
  (  SHIP_CABIN_ID, SHIP_ID, ROOM_NUMBER, ROOM_STYLE , ROOM_TYPE ,  WINDOW, GUESTS, SQ_FT, BALCONY_SQ_FT)
VALUES               
  (  SEQ_SHIP_CABIN_ID.NEXTVAL
                  , 1      , 106        , 'Suite'    , 'Standard', 'None' ,      6,   586, 193);
  
INSERT INTO SHIP_CABINS
  (  SHIP_CABIN_ID, SHIP_ID, ROOM_NUMBER, ROOM_STYLE , ROOM_TYPE ,  WINDOW, GUESTS, SQ_FT, BALCONY_SQ_FT)
VALUES               
  (  SEQ_SHIP_CABIN_ID.NEXTVAL
                  , 1      , 107        , 'Suite'    , 'Royal'   , 'Ocean',      5,  1524, 843);

INSERT INTO SHIP_CABINS
  (  SHIP_CABIN_ID, SHIP_ID, ROOM_NUMBER, ROOM_STYLE , ROOM_TYPE ,  WINDOW, GUESTS, SQ_FT, BALCONY_SQ_FT)
VALUES               
  (  SEQ_SHIP_CABIN_ID.NEXTVAL
                  , 1      , 108        , 'Stateroom', 'Large'   , 'None' ,      2,   211, NULL);

INSERT INTO SHIP_CABINS
  (  SHIP_CABIN_ID, SHIP_ID, ROOM_NUMBER, ROOM_STYLE , ROOM_TYPE ,  WINDOW, GUESTS, SQ_FT, BALCONY_SQ_FT)
VALUES               
  (  SEQ_SHIP_CABIN_ID.NEXTVAL
                  , 1      , 109        , 'Stateroom', 'Standard', 'None' ,      2,   180, NULL);

INSERT INTO SHIP_CABINS
  (  SHIP_CABIN_ID, SHIP_ID, ROOM_NUMBER, ROOM_STYLE , ROOM_TYPE ,  WINDOW, GUESTS, SQ_FT, BALCONY_SQ_FT)
VALUES               
  (  SEQ_SHIP_CABIN_ID.NEXTVAL
                  , 1      , 110        , 'Stateroom', 'Large'   , 'None' ,      2,   225, NULL);

INSERT INTO SHIP_CABINS
  (  SHIP_CABIN_ID, SHIP_ID, ROOM_NUMBER, ROOM_STYLE , ROOM_TYPE ,  WINDOW, GUESTS, SQ_FT, BALCONY_SQ_FT)
VALUES               
  (  SEQ_SHIP_CABIN_ID.NEXTVAL
                  , 1      , 702        , 'Suite'    , 'Presidential','None',    5,  1142, 476);

INSERT INTO SHIP_CABINS
  (  SHIP_CABIN_ID, SHIP_ID, ROOM_NUMBER, ROOM_STYLE , ROOM_TYPE ,  WINDOW, GUESTS, SQ_FT, BALCONY_SQ_FT)
VALUES               
  (  SEQ_SHIP_CABIN_ID.NEXTVAL
                  , 1      , 703        , 'Suite'    , 'Royal'   , 'Ocean' ,      5,  1745, 974);

INSERT INTO SHIP_CABINS
  (  SHIP_CABIN_ID, SHIP_ID, ROOM_NUMBER, ROOM_STYLE , ROOM_TYPE ,  WINDOW, GUESTS, SQ_FT, BALCONY_SQ_FT)
VALUES               
  (  SEQ_SHIP_CABIN_ID.NEXTVAL
                  , 1      , 704        , 'Suite'    , 'Skyloft' , 'Ocean' ,      8,   722, 410);

REM
REM INSERT INTO EMPLOYEES
REM

INSERT INTO EMPLOYEES
(  EMPLOYEE_ID, FIRST_NAME, LAST_NAME
 , POSITION_ID, SHIP_ID)
VALUES
(  SEQ_EMPLOYEE_ID.NEXTVAL
 , 'Howard','Hoddlestein'
 , 2, 1);

INSERT INTO EMPLOYEES
(  EMPLOYEE_ID, FIRST_NAME, LAST_NAME
 , POSITION_ID, SHIP_ID)
VALUES
(  SEQ_EMPLOYEE_ID.NEXTVAL
 , 'Joe','Smith'
 , 2, 3); 

INSERT INTO EMPLOYEES
(  EMPLOYEE_ID, FIRST_NAME, LAST_NAME
 , POSITION_ID, SHIP_ID)
VALUES
(  SEQ_EMPLOYEE_ID.NEXTVAL
 , 'Mike','West'
 , 2, 4);

INSERT INTO EMPLOYEES
(  EMPLOYEE_ID, FIRST_NAME, LAST_NAME
 , POSITION_ID, SHIP_ID)
VALUES
(  SEQ_EMPLOYEE_ID.NEXTVAL
 , 'Alice','Lindon'
 , 2, 3);

INSERT INTO EMPLOYEES
(  EMPLOYEE_ID, FIRST_NAME, LAST_NAME
 , POSITION_ID, SHIP_ID)
VALUES
(  SEQ_EMPLOYEE_ID.NEXTVAL
 , 'Al','Smith'
 , 2, 1);

INSERT INTO EMPLOYEES
(  EMPLOYEE_ID, FIRST_NAME, LAST_NAME
 , POSITION_ID, SHIP_ID)
VALUES
(  SEQ_EMPLOYEE_ID.NEXTVAL
 , 'Trish','West'
 , 2, 2);

INSERT INTO EMPLOYEES
(  EMPLOYEE_ID, FIRST_NAME, LAST_NAME
 , POSITION_ID, SHIP_ID)
VALUES
(  SEQ_EMPLOYEE_ID.NEXTVAL
 , 'Buffy','Worthington'
 , 2, 1);

REM
REM INSERT INTO ADDRESSES
REM

INSERT INTO ADDRESSES
  (  ADDRESS_ID
   , EMPLOYEE_ID
   , STREET_ADDRESS
   , STREET_ADDRESS2
   , CITY
   , STATE
   , ZIP
   , ZIP_PLUS
   , COUNTRY
   , CONTACT_EMAIL)
VALUES
  (  SEQ_ADDRESS_ID.NEXTVAL
   , 1
   , '350 Oracle Parkway'
   , NULL
   , 'Redwood City'
   , 'CA'
   , '94065'
   , NULL
   , 'USA'
   , NULL
   );

INSERT INTO ADDRESSES
  (  ADDRESS_ID
   , EMPLOYEE_ID
   , STREET_ADDRESS
   , STREET_ADDRESS2
   , CITY
   , STATE
   , ZIP
   , ZIP_PLUS
   , COUNTRY
   , CONTACT_EMAIL)
VALUES
  (  SEQ_ADDRESS_ID.NEXTVAL
   , 2
   , '1600 Amphitheatre Parkway'
   , NULL
   , 'Mountain View'
   , 'CA'
   , '94043'
   , NULL
   , 'USA'
   , NULL
   );

INSERT INTO ADDRESSES
  (  ADDRESS_ID
   , EMPLOYEE_ID
   , STREET_ADDRESS
   , STREET_ADDRESS2
   , CITY
   , STATE
   , ZIP
   , ZIP_PLUS
   , COUNTRY
   , CONTACT_EMAIL)
VALUES
  (  SEQ_ADDRESS_ID.NEXTVAL
   , 3
   , '1 Dell Way'
   , NULL
   , 'Round Rock'
   , 'TX'
   , '78682'
   , NULL
   , 'USA'
   , NULL
   );

INSERT INTO ADDRESSES
  (  ADDRESS_ID
   , EMPLOYEE_ID
   , STREET_ADDRESS
   , STREET_ADDRESS2
   , CITY
   , STATE
   , ZIP
   , ZIP_PLUS
   , COUNTRY
   , CONTACT_EMAIL)
VALUES
  (  SEQ_ADDRESS_ID.NEXTVAL
   , 4
   , '29 E Ohio St'
   , NULL
   , 'Chicago'
   , 'IL'
   , '60611'
   , '2707'
   , 'USA'
   , NULL
   );

INSERT INTO ADDRESSES
  (  ADDRESS_ID
   , EMPLOYEE_ID
   , STREET_ADDRESS
   , STREET_ADDRESS2
   , CITY
   , STATE
   , ZIP
   , ZIP_PLUS
   , COUNTRY
   , CONTACT_EMAIL)
VALUES
  (  SEQ_ADDRESS_ID.NEXTVAL
   , 5
   , '5788 Roswell Rd NE'
   , NULL
   , 'Atlanta'
   , 'GA'
   , '30328'
   , '4904'
   , 'USA'
   , NULL
   );

INSERT INTO ADDRESSES
  (  ADDRESS_ID
   , EMPLOYEE_ID
   , STREET_ADDRESS
   , STREET_ADDRESS2
   , CITY
   , STATE
   , ZIP
   , ZIP_PLUS
   , COUNTRY
   , CONTACT_EMAIL)
VALUES
  (  SEQ_ADDRESS_ID.NEXTVAL
   , 2
   , '10103 100 St NW'
   , NULL
   , 'Edmonton'
   , 'AB'
   , 'T5J'
   , '0N8'
   , 'Canada'
   , NULL
   );

INSERT INTO ADDRESSES
  (  ADDRESS_ID
   , EMPLOYEE_ID
   , STREET_ADDRESS
   , STREET_ADDRESS2
   , CITY
   , STATE
   , ZIP
   , ZIP_PLUS
   , COUNTRY
   , CONTACT_EMAIL)
VALUES
  (  SEQ_ADDRESS_ID.NEXTVAL
   , 6
   , '1221 Avenue of the Americas'
   , NULL
   , 'New York'
   , 'NY'
   , '10020'
   , NULL
   , 'USA'
   , NULL
   );

INSERT INTO ADDRESSES
  (  ADDRESS_ID
   , EMPLOYEE_ID
   , STREET_ADDRESS
   , STREET_ADDRESS2
   , CITY
   , STATE
   , ZIP
   , ZIP_PLUS
   , COUNTRY
   , CONTACT_EMAIL)
VALUES
  (  SEQ_ADDRESS_ID.NEXTVAL
   , 7
   , '239 Baker Street'
   , NULL
   , 'London'
   , NULL
   , 'NW1'
   , '6X3'
   , 'UK'
   , NULL
   );

INSERT INTO ADDRESSES
  (  ADDRESS_ID
   , EMPLOYEE_ID
   , STREET_ADDRESS
   , STREET_ADDRESS2
   , CITY
   , STATE
   , ZIP
   , ZIP_PLUS
   , COUNTRY
   , CONTACT_EMAIL)
VALUES
  (  SEQ_ADDRESS_ID.NEXTVAL
   , 7
   , '1 rue des Carrieres'
   , NULL
   , 'Quebec City'
   , 'QC'
   , 'G1R'
   , '4P5'
   , 'Canada'
   , NULL
   );

INSERT INTO ADDRESSES
  (  ADDRESS_ID
   , EMPLOYEE_ID
   , STREET_ADDRESS
   , STREET_ADDRESS2
   , CITY
   , STATE
   , ZIP
   , ZIP_PLUS
   , COUNTRY
   , CONTACT_EMAIL)
VALUES
  (  SEQ_ADDRESS_ID.NEXTVAL
   , 4
   , '2041 S Harbor Blvd'
   , NULL
   , 'Anaheim'
   , 'CA'
   , '92802'
   , '3513'
   , 'USA'
   , NULL
   );

INSERT INTO ADDRESSES
  (  ADDRESS_ID
   , EMPLOYEE_ID
   , STREET_ADDRESS
   , STREET_ADDRESS2
   , CITY
   , STATE
   , ZIP
   , ZIP_PLUS
   , COUNTRY
   , CONTACT_EMAIL)
VALUES
  (  SEQ_ADDRESS_ID.NEXTVAL
   , 2
   , '600 N Michigan Ave'
   , NULL
   , 'Chicago'
   , 'IL'
   , '60611'
   , '3113'
   , 'USA'
   , NULL
   );

INSERT INTO ADDRESSES
  (  ADDRESS_ID
   , EMPLOYEE_ID
   , STREET_ADDRESS
   , STREET_ADDRESS2
   , CITY
   , STATE
   , ZIP
   , ZIP_PLUS
   , COUNTRY
   , CONTACT_EMAIL)
VALUES
  (  SEQ_ADDRESS_ID.NEXTVAL
   , 6
   , '1515 Sheridan Rd'
   , NULL
   , 'Wilmette'
   , 'IL'
   , '60091'
   , NULL
   , 'USA'
   , NULL
   );

REM
REM INSERT INTO ONLINE_SUBSCRIBERS
REM

INSERT INTO ONLINE_SUBSCRIBERS
(  ONLINE_SUBSCRIBER_ID
 , LASTNAME
)
VALUES
(  SEQ_ONLINE_SUBSCRIBER_ID.NEXTVAL
 , 'KLINE'
); 

INSERT INTO ONLINE_SUBSCRIBERS
(  ONLINE_SUBSCRIBER_ID
 , LASTNAME
)
VALUES
(  SEQ_ONLINE_SUBSCRIBER_ID.NEXTVAL
 , 'bryant'
); 

INSERT INTO ONLINE_SUBSCRIBERS
(  ONLINE_SUBSCRIBER_ID
 , LASTNAME
)
VALUES
(  SEQ_ONLINE_SUBSCRIBER_ID.NEXTVAL
 , 'McLean'
); 

REM
REM INSERT INTO VENDORS
REM

INSERT INTO VENDORS 
  (VENDOR_ID, VENDOR_NAME)
  VALUES
  (SEQ_VENDOR_ID.NEXTVAL, 'Acme Steaks');

INSERT INTO VENDORS 
  (VENDOR_ID, VENDOR_NAME)
  VALUES
  (SEQ_VENDOR_ID.NEXTVAL, 'Acme Poker Chips');


REM
REM CREATE TABLE SCORES
REM

DROP   TABLE SCORES;
CREATE TABLE SCORES(
   SCORE_ID NUMBER
 , TEST_SCORE VARCHAR2(5)
 , UPDATED_TEST_SCORE VARCHAR2(5)
 , CONSTRAINT PK_SCORE_ID PRIMARY KEY (SCORE_ID)
);

REM
REM CREATE SEQUENCE SEQ_SCORE_ID
REM

DROP   SEQUENCE SEQ_SCORE_ID;
CREATE SEQUENCE SEQ_SCORE_ID;

REM
REM INSERT INTO SCORES
REM

INSERT INTO SCORES VALUES (SEQ_SCORE_ID.NEXTVAL,95,95);

INSERT INTO SCORES VALUES (SEQ_SCORE_ID.NEXTVAL,55,75);

INSERT INTO SCORES VALUES (SEQ_SCORE_ID.NEXTVAL,83,83);

REM
REM CREATE TABLE GRADING
REM

DROP   TABLE GRADING;
CREATE TABLE GRADING(
   GRADING_ID NUMBER
 , GRADE      CHAR(1)
 , SCORE_MIN  NUMBER(3)
 , SCORE_MAX  NUMBER(3)
 , CONSTRAINT PK_GRADING_ID PRIMARY KEY (GRADING_ID)
);

REM
REM CREATE SEQUENCE SEQ_GRADING_ID
REM

DROP   SEQUENCE SEQ_GRADING_ID;
CREATE SEQUENCE SEQ_GRADING_ID;

REM
REM INSERT INTO GRADING VALUES
REM

INSERT INTO GRADING VALUES 
           (SEQ_GRADING_ID.NEXTVAL, 'A', 90, 100);

INSERT INTO GRADING VALUES 
           (SEQ_GRADING_ID.NEXTVAL, 'B', 80, 89);

INSERT INTO GRADING VALUES 
           (SEQ_GRADING_ID.NEXTVAL, 'C', 70, 79);

INSERT INTO GRADING VALUES 
           (SEQ_GRADING_ID.NEXTVAL, 'D', 60, 69);

INSERT INTO GRADING VALUES 
           (SEQ_GRADING_ID.NEXTVAL, 'E', 50, 59);

COMMIT;

REM
REM You are ready to begin.
REM 
