REM
REM 5. Using Single-Row Functions to Customize Output
REM
REM Setup
REM

REM
REM CREATE TABLE EMPLOYEES
REM

CREATE TABLE EMPLOYEES
(  EMPLOYEE_ID         NUMBER(7)
 , SHIP_ID             NUMBER(7)
 , FIRST_NAME          VARCHAR2(20)
 , LAST_NAME           VARCHAR2(30)
 , POSITION_ID         NUMBER
 , SSN                 VARCHAR2(11)
 , DOB                 DATE
 , PRIMARY_PHONE       VARCHAR2(20)
 , CONSTRAINT          PK_EMPLOYEES 
                       PRIMARY KEY (EMPLOYEE_ID)
); 

REM
REM CREATE TABLE SHIPS
REM

CREATE TABLE SHIPS
(  SHIP_ID             NUMBER(7)
 , SHIP_NAME           VARCHAR2(20)
 , CAPACITY            NUMBER
 , LENGTH              NUMBER
 , HOME_PORT_ID        NUMBER
 , CONSTRAINT          PK_SHIP 
                       PRIMARY KEY (SHIP_ID)
);

REM
REM CREATE TABLE SHIP_CABINS
REM

CREATE TABLE SHIP_CABINS
(  SHIP_CABIN_ID       NUMBER
 , SHIP_ID             NUMBER(7)
 , ROOM_NUMBER         VARCHAR2(5)
 , ROOM_STYLE          VARCHAR2(10)
 , ROOM_TYPE           VARCHAR2(20)
 , WINDOW              VARCHAR2(10)
 , GUESTS              NUMBER(3)
 , SQ_FT               NUMBER(6)
 , BALCONY_SQ_FT       NUMBER(6)
 , CONSTRAINT          PK_SHIP_CABIN_ID 
                       PRIMARY KEY (SHIP_CABIN_ID)
 , CONSTRAINT          CK_WINDOW 
                       CHECK (WINDOW IN ('Ocean',
                              'Balcony', 'None'))
);

REM
REM CREATE TABLE ADDRESSES
REM

CREATE TABLE ADDRESSES
(
   ADDRESS_ID          NUMBER
 , EMPLOYEE_ID         NUMBER
 , STREET_ADDRESS      VARCHAR2(40)
 , STREET_ADDRESS2     VARCHAR2(40)
 , CITY                VARCHAR2(30)
 , STATE               VARCHAR2(2)
 , ZIP                 VARCHAR2(5)
 , ZIP_PLUS            VARCHAR2(4)
 , COUNTRY             VARCHAR2(20)
 , CONTACT_EMAIL       VARCHAR2(80)
 , CONSTRAINT          PK_ADDRESS_ID
                       PRIMARY KEY (ADDRESS_ID)
);

REM
REM CREATE TABLE ONLINE_SUBSCRIBERS
REM

CREATE TABLE ONLINE_SUBSCRIBERS
(
   ONLINE_SUBSCRIBER_ID NUMBER
 , SUB_DATE             DATE
 , EMAIL                VARCHAR2(120)
 , FIRSTNAME            VARCHAR2(20)
 , LASTNAME             VARCHAR2(30)
 , COMPANY              VARCHAR2(30)
 , CONSTRAINT           PK_ONLINE_SUBSCRIBER_ID
                        PRIMARY KEY (ONLINE_SUBSCRIBER_ID)
);

REM
REM CREATE SEQUENCE SEQ_ONLINE_SUBSCRIBER_ID
REM

CREATE SEQUENCE SEQ_ONLINE_SUBSCRIBER_ID;

REM
REM CREATE SEQUENCE SEQ_EMPLOYEE_ID
REM

CREATE SEQUENCE SEQ_EMPLOYEE_ID;

REM
REM CREATE SEQUENCE SEQ_SHIP_ID
REM

CREATE SEQUENCE SEQ_SHIP_ID;

REM
REM CREATE SEQUENCE SEQ_SHIP_CABIN_ID
REM

CREATE SEQUENCE SEQ_SHIP_CABIN_ID;

REM
REM CREATE SEQUENCE SEQ_ADDRESS_ID
REM

CREATE SEQUENCE SEQ_ADDRESS_ID;

REM
REM INSERT INTO EMPLOYEES
REM

INSERT INTO EMPLOYEES
(  EMPLOYEE_ID, FIRST_NAME, LAST_NAME
 , POSITION_ID, SHIP_ID)
VALUES
(  SEQ_EMPLOYEE_ID.NEXTVAL
 , 'Mike','West'
 , 2, 4);

INSERT INTO EMPLOYEES
(  EMPLOYEE_ID, FIRST_NAME, LAST_NAME
 , POSITION_ID, SHIP_ID)
VALUES
(  SEQ_EMPLOYEE_ID.NEXTVAL
 , 'Alice','Lindon'
 , 2, 3);

INSERT INTO EMPLOYEES
(  EMPLOYEE_ID, FIRST_NAME, LAST_NAME
 , POSITION_ID, SHIP_ID)
VALUES
(  SEQ_EMPLOYEE_ID.NEXTVAL
 , 'Al','Smith'
 , 2, 1);

INSERT INTO EMPLOYEES
(  EMPLOYEE_ID, FIRST_NAME, LAST_NAME
 , POSITION_ID, SHIP_ID)
VALUES
(  SEQ_EMPLOYEE_ID.NEXTVAL
 , 'Fred','McGillicutty'
 , 2, 1);

INSERT INTO EMPLOYEES
(  EMPLOYEE_ID, FIRST_NAME, LAST_NAME
 , POSITION_ID, SHIP_ID)
VALUES
(  SEQ_EMPLOYEE_ID.NEXTVAL
 , 'Trish','West'
 , 2, 2);

INSERT INTO EMPLOYEES
(  EMPLOYEE_ID, FIRST_NAME, LAST_NAME
 , POSITION_ID, SHIP_ID)
VALUES
(  SEQ_EMPLOYEE_ID.NEXTVAL
 , 'Buffy','Worthington'
 , 2, 1);

REM
REM INSERT INTO SHIPS
REM

INSERT INTO SHIPS
(  SHIP_ID, SHIP_NAME, CAPACITY, LENGTH, HOME_PORT_ID)
VALUES
(  SEQ_SHIP_ID.NEXTVAL
 , 'Codd Crystal', 2052, 855, 1) 
;

INSERT INTO SHIPS
(  SHIP_ID, SHIP_NAME, CAPACITY, LENGTH, HOME_PORT_ID)
VALUES
(  SEQ_SHIP_ID.NEXTVAL
 , 'Codd Elegance', 2974, 952, 3) 
;

INSERT INTO SHIPS
(  SHIP_ID, SHIP_NAME, CAPACITY, LENGTH, HOME_PORT_ID)
VALUES
(  SEQ_SHIP_ID.NEXTVAL
 , 'Codd Champion', 2974, 952, NULL) 
;

INSERT INTO SHIPS
(  SHIP_ID, SHIP_NAME, CAPACITY, LENGTH, HOME_PORT_ID)
VALUES
(  SEQ_SHIP_ID.NEXTVAL
 , 'Codd Victorious', 2974, 952, 3) 
;

INSERT INTO SHIPS
(  SHIP_ID, SHIP_NAME, CAPACITY, LENGTH, HOME_PORT_ID)
VALUES
(  SEQ_SHIP_ID.NEXTVAL
 , 'Codd Grandeur', 2446, 916, 2) 
;

INSERT INTO SHIPS
(  SHIP_ID, SHIP_NAME, CAPACITY, LENGTH, HOME_PORT_ID)
VALUES
(  SEQ_SHIP_ID.NEXTVAL
 , 'Codd Prince', 395, 470, 2) 
;

INSERT INTO SHIPS
(  SHIP_ID, SHIP_NAME, CAPACITY, LENGTH, HOME_PORT_ID)
VALUES
(  SEQ_SHIP_ID.NEXTVAL
 , 'Codd Harmony', 940, 790, 2) 
;

INSERT INTO SHIPS
(  SHIP_ID, SHIP_NAME, CAPACITY, LENGTH, HOME_PORT_ID)
VALUES
(  SEQ_SHIP_ID.NEXTVAL
 , 'Codd Voyager', 3114, 1020, 2) 
;

REM
REM INSERT INTO ADDRESSES 
REM

INSERT INTO ADDRESSES
  (  ADDRESS_ID
   , EMPLOYEE_ID
   , STREET_ADDRESS
   , STREET_ADDRESS2
   , CITY
   , STATE
   , ZIP
   , ZIP_PLUS
   , COUNTRY
   , CONTACT_EMAIL)
VALUES
  (  SEQ_ADDRESS_ID.NEXTVAL
   , 1
   , '350 Oracle Parkway'
   , NULL
   , 'Redwood City'
   , 'CA'
   , '94065'
   , NULL
   , 'USA'
   , NULL
   );

INSERT INTO ADDRESSES
  (  ADDRESS_ID
   , EMPLOYEE_ID
   , STREET_ADDRESS
   , STREET_ADDRESS2
   , CITY
   , STATE
   , ZIP
   , ZIP_PLUS
   , COUNTRY
   , CONTACT_EMAIL)
VALUES
  (  SEQ_ADDRESS_ID.NEXTVAL
   , 3
   , '1 Dell Way'
   , NULL
   , 'Round Rock'
   , 'TX'
   , '78682'
   , NULL
   , 'USA'
   , NULL
   );

INSERT INTO ADDRESSES
  (  ADDRESS_ID
   , EMPLOYEE_ID
   , STREET_ADDRESS
   , STREET_ADDRESS2
   , CITY
   , STATE
   , ZIP
   , ZIP_PLUS
   , COUNTRY
   , CONTACT_EMAIL)
VALUES
  (  SEQ_ADDRESS_ID.NEXTVAL
   , 4
   , '29 E Ohio St'
   , NULL
   , 'Chicago'
   , 'IL'
   , '60611'
   , '2707'
   , 'USA'
   , NULL
   );

INSERT INTO ADDRESSES
  (  ADDRESS_ID
   , EMPLOYEE_ID
   , STREET_ADDRESS
   , STREET_ADDRESS2
   , CITY
   , STATE
   , ZIP
   , ZIP_PLUS
   , COUNTRY
   , CONTACT_EMAIL)
VALUES
  (  SEQ_ADDRESS_ID.NEXTVAL
   , 2
   , '10103 100 St NW'
   , NULL
   , 'Edmonton'
   , 'AB'
   , 'T5J'
   , '0N8'
   , 'Canada'
   , NULL
   );


INSERT INTO ADDRESSES
  (  ADDRESS_ID
   , EMPLOYEE_ID
   , STREET_ADDRESS
   , STREET_ADDRESS2
   , CITY
   , STATE
   , ZIP
   , ZIP_PLUS
   , COUNTRY
   , CONTACT_EMAIL)
VALUES
  (  SEQ_ADDRESS_ID.NEXTVAL
   , 6
   , '1221 Avenue of the Americas'
   , NULL
   , 'New York'
   , 'NY'
   , '10020'
   , NULL
   , 'USA'
   , NULL
   );

INSERT INTO ADDRESSES
  (  ADDRESS_ID
   , EMPLOYEE_ID
   , STREET_ADDRESS
   , STREET_ADDRESS2
   , CITY
   , STATE
   , ZIP
   , ZIP_PLUS
   , COUNTRY
   , CONTACT_EMAIL)
VALUES
  (  SEQ_ADDRESS_ID.NEXTVAL
   , 7
   , '239 Baker Street'
   , NULL
   , 'London'
   , NULL
   , 'NW1'
   , '6X3'
   , 'UK'
   , NULL
   );

INSERT INTO ADDRESSES
  (  ADDRESS_ID
   , EMPLOYEE_ID
   , STREET_ADDRESS
   , STREET_ADDRESS2
   , CITY
   , STATE
   , ZIP
   , ZIP_PLUS
   , COUNTRY
   , CONTACT_EMAIL)
VALUES
  (  SEQ_ADDRESS_ID.NEXTVAL
   , 7
   , '1 rue des Carrieres'
   , NULL
   , 'Quebec City'
   , 'QC'
   , 'G1R'
   , '4P5'
   , 'Canada'
   , NULL
   );

REM
REM INSERT INTO ONLINE_SUBSCRIBERS 
REM

INSERT INTO ONLINE_SUBSCRIBERS
(  ONLINE_SUBSCRIBER_ID
 , SUB_DATE
 , EMAIL
 , FIRSTNAME
 , LASTNAME
 , COMPANY)
VALUES
(  SEQ_ONLINE_SUBSCRIBER_ID.NEXTVAL
 , '12-DEC-08'
 , 'pendicott77@kasteelinc.com'
 , 'EDGAR'
 , 'KLINE'
 , 'KLINE AND ASSOCIATES'
); 

INSERT INTO ONLINE_SUBSCRIBERS
(  ONLINE_SUBSCRIBER_ID
 , SUB_DATE
 , EMAIL
 , FIRSTNAME
 , LASTNAME
 , COMPANY)
VALUES
(  SEQ_ONLINE_SUBSCRIBER_ID.NEXTVAL
 , '09-APR-09'
 , 'watcher@foursigma.org'
 , 'bill'
 , 'bryant'
 , 'Gold International'
); 

INSERT INTO ONLINE_SUBSCRIBERS
(  ONLINE_SUBSCRIBER_ID
 , SUB_DATE
 , EMAIL
 , FIRSTNAME
 , LASTNAME
 , COMPANY)
VALUES
(  SEQ_ONLINE_SUBSCRIBER_ID.NEXTVAL
 , '09-APR-09'
 , 'hardingpal@ckofca.com'
 , 'Ned'
 , 'McLean'
 , 'Harding Company'
); 

REM
REM INSERT INTO SHIP_CABINS  
REM

INSERT INTO SHIP_CABINS
  (  SHIP_CABIN_ID, SHIP_ID, ROOM_NUMBER, ROOM_STYLE , ROOM_TYPE ,  WINDOW, GUESTS, SQ_FT, BALCONY_SQ_FT)
VALUES               
  (  SEQ_SHIP_CABIN_ID.NEXTVAL
                  , 1      , 102        , 'Suite'    , 'Standard', 'Ocean',      4,   533, 139);

INSERT INTO SHIP_CABINS
  (  SHIP_CABIN_ID, SHIP_ID, ROOM_NUMBER, ROOM_STYLE , ROOM_TYPE ,  WINDOW, GUESTS, SQ_FT, BALCONY_SQ_FT)
VALUES               
  (  SEQ_SHIP_CABIN_ID.NEXTVAL
                  , 1      , 103        , 'Stateroom', 'Standard', 'Ocean',      2,   160, NULL);

INSERT INTO SHIP_CABINS
  (  SHIP_CABIN_ID, SHIP_ID, ROOM_NUMBER, ROOM_STYLE , ROOM_TYPE ,  WINDOW, GUESTS, SQ_FT, BALCONY_SQ_FT)
VALUES               
  (  SEQ_SHIP_CABIN_ID.NEXTVAL
                  , 1      , 104        , 'Suite'    , 'Standard', 'None' ,      4,   533, 139);

INSERT INTO SHIP_CABINS
  (  SHIP_CABIN_ID, SHIP_ID, ROOM_NUMBER, ROOM_STYLE , ROOM_TYPE ,  WINDOW, GUESTS, SQ_FT, BALCONY_SQ_FT)
VALUES               
  (  SEQ_SHIP_CABIN_ID.NEXTVAL
                  , 1      , 105        , 'Stateroom', 'Standard', 'Ocean',      3,   205, NULL);

INSERT INTO SHIP_CABINS
  (  SHIP_CABIN_ID, SHIP_ID, ROOM_NUMBER, ROOM_STYLE , ROOM_TYPE ,  WINDOW, GUESTS, SQ_FT, BALCONY_SQ_FT)
VALUES               
  (  SEQ_SHIP_CABIN_ID.NEXTVAL
                  , 1      , 106        , 'Suite'    , 'Standard', 'None' ,      6,   586, 193);
  
INSERT INTO SHIP_CABINS
  (  SHIP_CABIN_ID, SHIP_ID, ROOM_NUMBER, ROOM_STYLE , ROOM_TYPE ,  WINDOW, GUESTS, SQ_FT, BALCONY_SQ_FT)
VALUES               
  (  SEQ_SHIP_CABIN_ID.NEXTVAL
                  , 1      , 107        , 'Suite'    , 'Royal'   , 'Ocean',      5,  1524, 843);

INSERT INTO SHIP_CABINS
  (  SHIP_CABIN_ID, SHIP_ID, ROOM_NUMBER, ROOM_STYLE , ROOM_TYPE ,  WINDOW, GUESTS, SQ_FT, BALCONY_SQ_FT)
VALUES               
  (  SEQ_SHIP_CABIN_ID.NEXTVAL
                  , 1      , 108        , 'Stateroom', 'Large'   , 'None' ,      2,   211, NULL);

INSERT INTO SHIP_CABINS
  (  SHIP_CABIN_ID, SHIP_ID, ROOM_NUMBER, ROOM_STYLE , ROOM_TYPE ,  WINDOW, GUESTS, SQ_FT, BALCONY_SQ_FT)
VALUES               
  (  SEQ_SHIP_CABIN_ID.NEXTVAL
                  , 1      , 109        , 'Stateroom', 'Standard', 'None' ,      2,   180, NULL);

INSERT INTO SHIP_CABINS
  (  SHIP_CABIN_ID, SHIP_ID, ROOM_NUMBER, ROOM_STYLE , ROOM_TYPE ,  WINDOW, GUESTS, SQ_FT, BALCONY_SQ_FT)
VALUES               
  (  SEQ_SHIP_CABIN_ID.NEXTVAL
                  , 1      , 110        , 'Stateroom', 'Large'   , 'None' ,      2,   225, NULL);

INSERT INTO SHIP_CABINS
  (  SHIP_CABIN_ID, SHIP_ID, ROOM_NUMBER, ROOM_STYLE , ROOM_TYPE ,  WINDOW, GUESTS, SQ_FT, BALCONY_SQ_FT)
VALUES               
  (  SEQ_SHIP_CABIN_ID.NEXTVAL
                  , 1      , 702        , 'Suite'    , 'Presidential','None',    5,  1142, 476);

INSERT INTO SHIP_CABINS
  (  SHIP_CABIN_ID, SHIP_ID, ROOM_NUMBER, ROOM_STYLE , ROOM_TYPE ,  WINDOW, GUESTS, SQ_FT, BALCONY_SQ_FT)
VALUES               
  (  SEQ_SHIP_CABIN_ID.NEXTVAL
                  , 1      , 703        , 'Suite'    , 'Royal'   , 'Ocean' ,      5,  1745, 974);

INSERT INTO SHIP_CABINS
  (  SHIP_CABIN_ID, SHIP_ID, ROOM_NUMBER, ROOM_STYLE , ROOM_TYPE ,  WINDOW, GUESTS, SQ_FT, BALCONY_SQ_FT)
VALUES               
  (  SEQ_SHIP_CABIN_ID.NEXTVAL
                  , 1      , 704        , 'Suite'    , 'Skyloft' , 'Ocean' ,      8,   722, 410);

REM
REM INSERT INTO BOOK_CONTENTS 
REM

CREATE TABLE BOOK_CONTENTS
(  BOOK_CONTENT_ID   NUMBER
 , CHAPTER_TITLE     VARCHAR2(30)
 , PAGE_NUMBER       NUMBER(4)
);

REM
REM CREATE SEQUENCE SEQ_BOOK_CONTENT_ID 
REM

CREATE SEQUENCE SEQ_BOOK_CONTENT_ID;

REM
REM INSERT INTO BOOK_CONTENTS
REM

INSERT INTO BOOK_CONTENTS
  (  BOOK_CONTENT_ID   , CHAPTER_TITLE
   , PAGE_NUMBER)
  VALUES
  (  SEQ_BOOK_CONTENT_ID.NEXTVAL
   , 'Introduction'
   , 1);

INSERT INTO BOOK_CONTENTS
  (  BOOK_CONTENT_ID
   , CHAPTER_TITLE
   , PAGE_NUMBER)
  VALUES
  (  SEQ_BOOK_CONTENT_ID.NEXTVAL
   , 'Chapter 1'
   , 5);

INSERT INTO BOOK_CONTENTS
  (  BOOK_CONTENT_ID
   , CHAPTER_TITLE
   , PAGE_NUMBER)
  VALUES
  (  SEQ_BOOK_CONTENT_ID.NEXTVAL
   , 'Chapter 2'
   , 23);

INSERT INTO BOOK_CONTENTS
  (  BOOK_CONTENT_ID
   , CHAPTER_TITLE
   , PAGE_NUMBER)
  VALUES
  (  SEQ_BOOK_CONTENT_ID.NEXTVAL
   , 'Chapter 3'
   , 57);

INSERT INTO BOOK_CONTENTS
  (  BOOK_CONTENT_ID
   , CHAPTER_TITLE
   , PAGE_NUMBER)
  VALUES
  (  SEQ_BOOK_CONTENT_ID.NEXTVAL
   , 'Index'
   , 79);

REM
REM CREATE TABLE SCORES 
REM

CREATE TABLE SCORES(
   SCORE_ID NUMBER
 , TEST_SCORE VARCHAR2(5)
 , UPDATED_TEST_SCORE VARCHAR2(5)
 , CONSTRAINT PK_SCORE_ID PRIMARY KEY (SCORE_ID)
);

REM
REM CREATE SEQUENCE   
REM

CREATE SEQUENCE SEQ_SCORE_ID;

REM
REM INSERT INTO SCORES 
REM

INSERT INTO SCORES VALUES (SEQ_SCORE_ID.NEXTVAL,95,95);
INSERT INTO SCORES VALUES (SEQ_SCORE_ID.NEXTVAL,55,75);
INSERT INTO SCORES VALUES (SEQ_SCORE_ID.NEXTVAL,83,83);

REM
REM CREATE TABLE CALLS
REM

CREATE TABLE CALLS 
(   CALL_ID NUMBER
, CALL_DATE_TZ TIMESTAMP WITH TIME ZONE);


REM 
REM You are ready to begin.
REM
