SET ECHO ON

REM
REM 4. Restricting and Sorting Data - Setup 2 of 2
REM
REM Setup for the section on PIVOT and UNPIVOT
REM

REM
REM CREATE TABLE SHIP_CABINS
REM

DROP   TABLE SHIP_CABINS;
CREATE TABLE SHIP_CABINS
(  SHIP_CABIN_ID       NUMBER
 , SHIP_ID             NUMBER(7)
 , ROOM_NUMBER         VARCHAR2(5)
 , ROOM_STYLE          VARCHAR2(10)
 , ROOM_TYPE           VARCHAR2(20)
 , WINDOW              VARCHAR2(10)
 , GUESTS              NUMBER(3)
 , SQ_FT               NUMBER(6)
 , BALCONY_SQ_FT       NUMBER(6)
 , CONSTRAINT          PK_SHIP_CABIN_ID 
                       PRIMARY KEY (SHIP_CABIN_ID)
 , CONSTRAINT          CK_WINDOW 
                       CHECK (WINDOW IN ('Ocean',
                              'Balcony', 'None'))
);

REM
REM CREATE SEQUENCE SEQ_SHIP_ID
REM

DROP   SEQUENCE SEQ_SHIP_ID;
CREATE SEQUENCE SEQ_SHIP_ID;

REM
REM INSERT INTO SHIP_CABINS
REM

INSERT INTO SHIP_CABINS
  (  SHIP_CABIN_ID, SHIP_ID, ROOM_NUMBER, ROOM_STYLE , ROOM_TYPE ,  WINDOW, GUESTS, SQ_FT, BALCONY_SQ_FT)
VALUES               
  (  SEQ_SHIP_CABIN_ID.NEXTVAL
                  , 1      , 102        , 'Suite'    , 'Standard', 'Balcony',      4,   533, 139);

INSERT INTO SHIP_CABINS
  (  SHIP_CABIN_ID, SHIP_ID, ROOM_NUMBER, ROOM_STYLE , ROOM_TYPE ,  WINDOW, GUESTS, SQ_FT, BALCONY_SQ_FT)
VALUES               
  (  SEQ_SHIP_CABIN_ID.NEXTVAL
                  , 1      , 103        , 'Stateroom', 'Standard', 'Ocean',      2,   160, NULL);

INSERT INTO SHIP_CABINS
  (  SHIP_CABIN_ID, SHIP_ID, ROOM_NUMBER, ROOM_STYLE , ROOM_TYPE ,  WINDOW, GUESTS, SQ_FT, BALCONY_SQ_FT)
VALUES               
  (  SEQ_SHIP_CABIN_ID.NEXTVAL
                  , 1      , 104        , 'Suite'    , 'Standard', 'Balcony' ,      4,   533, 139);

INSERT INTO SHIP_CABINS
  (  SHIP_CABIN_ID, SHIP_ID, ROOM_NUMBER, ROOM_STYLE , ROOM_TYPE ,  WINDOW, GUESTS, SQ_FT, BALCONY_SQ_FT)
VALUES               
  (  SEQ_SHIP_CABIN_ID.NEXTVAL
                  , 1      , 105        , 'Stateroom', 'Standard', 'Ocean',      3,   205, NULL);

INSERT INTO SHIP_CABINS
  (  SHIP_CABIN_ID, SHIP_ID, ROOM_NUMBER, ROOM_STYLE , ROOM_TYPE ,  WINDOW, GUESTS, SQ_FT, BALCONY_SQ_FT)
VALUES               
  (  SEQ_SHIP_CABIN_ID.NEXTVAL
                  , 1      , 106        , 'Suite'    , 'Standard', 'Balcony' ,      6,   586, 193);
  
INSERT INTO SHIP_CABINS
  (  SHIP_CABIN_ID, SHIP_ID, ROOM_NUMBER, ROOM_STYLE , ROOM_TYPE ,  WINDOW, GUESTS, SQ_FT, BALCONY_SQ_FT)
VALUES               
  (  SEQ_SHIP_CABIN_ID.NEXTVAL
                  , 1      , 107        , 'Suite'    , 'Royal'   , 'Balcony',      5,  1524, 843);

INSERT INTO SHIP_CABINS
  (  SHIP_CABIN_ID, SHIP_ID, ROOM_NUMBER, ROOM_STYLE , ROOM_TYPE ,  WINDOW, GUESTS, SQ_FT, BALCONY_SQ_FT)
VALUES               
  (  SEQ_SHIP_CABIN_ID.NEXTVAL
                  , 1      , 108        , 'Stateroom', 'Large'   , 'None' ,      2,   211, NULL);

INSERT INTO SHIP_CABINS
  (  SHIP_CABIN_ID, SHIP_ID, ROOM_NUMBER, ROOM_STYLE , ROOM_TYPE ,  WINDOW, GUESTS, SQ_FT, BALCONY_SQ_FT)
VALUES               
  (  SEQ_SHIP_CABIN_ID.NEXTVAL
                  , 1      , 109        , 'Stateroom', 'Standard', 'Ocean' ,      2,   180, NULL);

INSERT INTO SHIP_CABINS
  (  SHIP_CABIN_ID, SHIP_ID, ROOM_NUMBER, ROOM_STYLE , ROOM_TYPE ,  WINDOW, GUESTS, SQ_FT, BALCONY_SQ_FT)
VALUES               
  (  SEQ_SHIP_CABIN_ID.NEXTVAL
                  , 1      , 110        , 'Stateroom', 'Large'   , 'Ocean' ,      2,   225, NULL);

INSERT INTO SHIP_CABINS
  (  SHIP_CABIN_ID, SHIP_ID, ROOM_NUMBER, ROOM_STYLE , ROOM_TYPE ,  WINDOW, GUESTS, SQ_FT, BALCONY_SQ_FT)
VALUES               
  (  SEQ_SHIP_CABIN_ID.NEXTVAL
                  , 1      , 701        , 'Suite'    , 'Presidential','Balcony',    5,  1142, 476);

INSERT INTO SHIP_CABINS
  (  SHIP_CABIN_ID, SHIP_ID, ROOM_NUMBER, ROOM_STYLE , ROOM_TYPE ,  WINDOW, GUESTS, SQ_FT, BALCONY_SQ_FT)
VALUES               
  (  SEQ_SHIP_CABIN_ID.NEXTVAL
                  , 1      , 702        , 'Suite'    , 'Presidential','Balcony',    5,  1142, 476);

INSERT INTO SHIP_CABINS
  (  SHIP_CABIN_ID, SHIP_ID, ROOM_NUMBER, ROOM_STYLE , ROOM_TYPE ,  WINDOW, GUESTS, SQ_FT, BALCONY_SQ_FT)
VALUES               
  (  SEQ_SHIP_CABIN_ID.NEXTVAL
                  , 1      , 703        , 'Suite'    , 'Royal'   , 'Balcony' ,      5,  1745, 974);

INSERT INTO SHIP_CABINS
  (  SHIP_CABIN_ID, SHIP_ID, ROOM_NUMBER, ROOM_STYLE , ROOM_TYPE ,  WINDOW, GUESTS, SQ_FT, BALCONY_SQ_FT)
VALUES               
  (  SEQ_SHIP_CABIN_ID.NEXTVAL
                  , 1      , 704        , 'Suite'    , 'Skyloft' , 'Balcony' ,      8,   722, 410);

INSERT INTO SHIP_CABINS
  (  SHIP_CABIN_ID, SHIP_ID, ROOM_NUMBER, ROOM_STYLE , ROOM_TYPE ,  WINDOW, GUESTS, SQ_FT, BALCONY_SQ_FT)
VALUES               
  (  SEQ_SHIP_CABIN_ID.NEXTVAL
                  , 1      , 705        , 'Stateroom' , 'Standard' , 'Ocean' ,     2,   160, NULL);

INSERT INTO SHIP_CABINS
  (  SHIP_CABIN_ID, SHIP_ID, ROOM_NUMBER, ROOM_STYLE , ROOM_TYPE ,  WINDOW, GUESTS, SQ_FT, BALCONY_SQ_FT)
VALUES               
  (  SEQ_SHIP_CABIN_ID.NEXTVAL
                  , 1      , 706        , 'Suite' , 'Standard' , 'Balcony' ,     4,   533, 139);

INSERT INTO SHIP_CABINS
  (  SHIP_CABIN_ID, SHIP_ID, ROOM_NUMBER, ROOM_STYLE , ROOM_TYPE ,  WINDOW, GUESTS, SQ_FT, BALCONY_SQ_FT)
VALUES               
  (  SEQ_SHIP_CABIN_ID.NEXTVAL
                  , 1      , 707        , 'Stateroom' , 'Standard' , 'Ocean' ,     3,   205, NULL);

INSERT INTO SHIP_CABINS
  (  SHIP_CABIN_ID, SHIP_ID, ROOM_NUMBER, ROOM_STYLE , ROOM_TYPE ,  WINDOW, GUESTS, SQ_FT, BALCONY_SQ_FT)
VALUES               
  (  SEQ_SHIP_CABIN_ID.NEXTVAL
                  , 1      , 708        , 'Suite' , 'Standard' , 'Balcony' ,     6,   586, 193);

INSERT INTO SHIP_CABINS
  (  SHIP_CABIN_ID, SHIP_ID, ROOM_NUMBER, ROOM_STYLE , ROOM_TYPE ,  WINDOW, GUESTS, SQ_FT, BALCONY_SQ_FT)
VALUES               
  (  SEQ_SHIP_CABIN_ID.NEXTVAL
                  , 1      , 709        , 'Stateroom' , 'Large' , 'None' ,     2,   211, NULL);

INSERT INTO SHIP_CABINS
  (  SHIP_CABIN_ID, SHIP_ID, ROOM_NUMBER, ROOM_STYLE , ROOM_TYPE ,  WINDOW, GUESTS, SQ_FT, BALCONY_SQ_FT)
VALUES               
  (  SEQ_SHIP_CABIN_ID.NEXTVAL
                  , 1      , 710        , 'Stateroom' , 'Standard' , 'Ocean' ,     2,   180, NULL);

INSERT INTO SHIP_CABINS
  (  SHIP_CABIN_ID, SHIP_ID, ROOM_NUMBER, ROOM_STYLE , ROOM_TYPE ,  WINDOW, GUESTS, SQ_FT, BALCONY_SQ_FT)
VALUES               
  (  SEQ_SHIP_CABIN_ID.NEXTVAL
                  , 1      , 801        , 'Suite'    , 'Presidential','None',    5,  1142, NULL);

INSERT INTO SHIP_CABINS
  (  SHIP_CABIN_ID, SHIP_ID, ROOM_NUMBER, ROOM_STYLE , ROOM_TYPE ,  WINDOW, GUESTS, SQ_FT, BALCONY_SQ_FT)
VALUES               
  (  SEQ_SHIP_CABIN_ID.NEXTVAL
                  , 1      , 802        , 'Suite'    , 'Presidential','Ocean',    5,  1142, NULL);

INSERT INTO SHIP_CABINS
  (  SHIP_CABIN_ID, SHIP_ID, ROOM_NUMBER, ROOM_STYLE , ROOM_TYPE ,  WINDOW, GUESTS, SQ_FT, BALCONY_SQ_FT)
VALUES               
  (  SEQ_SHIP_CABIN_ID.NEXTVAL
                  , 1      , 803        , 'Suite'    , 'Royal'   , 'Ocean' ,      5,  1745, NULL);

INSERT INTO SHIP_CABINS
  (  SHIP_CABIN_ID, SHIP_ID, ROOM_NUMBER, ROOM_STYLE , ROOM_TYPE ,  WINDOW, GUESTS, SQ_FT, BALCONY_SQ_FT)
VALUES               
  (  SEQ_SHIP_CABIN_ID.NEXTVAL
                  , 1      , 804        , 'Suite'    , 'Skyloft' , 'Ocean' ,      8,   722, NULL);

INSERT INTO SHIP_CABINS
  (  SHIP_CABIN_ID, SHIP_ID, ROOM_NUMBER, ROOM_STYLE , ROOM_TYPE ,  WINDOW, GUESTS, SQ_FT, BALCONY_SQ_FT)
VALUES               
  (  SEQ_SHIP_CABIN_ID.NEXTVAL
                  , 1      , 805        , 'Stateroom' , 'Standard' , 'Ocean' ,     2,   160, NULL);

INSERT INTO SHIP_CABINS
  (  SHIP_CABIN_ID, SHIP_ID, ROOM_NUMBER, ROOM_STYLE , ROOM_TYPE ,  WINDOW, GUESTS, SQ_FT, BALCONY_SQ_FT)
VALUES               
  (  SEQ_SHIP_CABIN_ID.NEXTVAL
                  , 1      , 806        , 'Suite' , 'Standard' , 'Ocean' ,     4,   533, NULL);

INSERT INTO SHIP_CABINS
  (  SHIP_CABIN_ID, SHIP_ID, ROOM_NUMBER, ROOM_STYLE , ROOM_TYPE ,  WINDOW, GUESTS, SQ_FT, BALCONY_SQ_FT)
VALUES               
  (  SEQ_SHIP_CABIN_ID.NEXTVAL
                  , 1      , 807        , 'Stateroom' , 'Standard' , 'Ocean' ,     3,   205, NULL);

INSERT INTO SHIP_CABINS
  (  SHIP_CABIN_ID, SHIP_ID, ROOM_NUMBER, ROOM_STYLE , ROOM_TYPE ,  WINDOW, GUESTS, SQ_FT, BALCONY_SQ_FT)
VALUES               
  (  SEQ_SHIP_CABIN_ID.NEXTVAL
                  , 1      , 808        , 'Suite' , 'Standard' , 'None' ,     6,   586, NULL);

INSERT INTO SHIP_CABINS
  (  SHIP_CABIN_ID, SHIP_ID, ROOM_NUMBER, ROOM_STYLE , ROOM_TYPE ,  WINDOW, GUESTS, SQ_FT, BALCONY_SQ_FT)
VALUES               
  (  SEQ_SHIP_CABIN_ID.NEXTVAL
                  , 1      , 809        , 'Stateroom' , 'Large' , 'None' ,     2,   211, NULL);

INSERT INTO SHIP_CABINS
  (  SHIP_CABIN_ID, SHIP_ID, ROOM_NUMBER, ROOM_STYLE , ROOM_TYPE ,  WINDOW, GUESTS, SQ_FT, BALCONY_SQ_FT)
VALUES               
  (  SEQ_SHIP_CABIN_ID.NEXTVAL
                  , 1      , 810        , 'Stateroom' , 'Standard' , 'Ocean' ,     2,   180, NULL);



DROP   TABLE SITE_LOG_SUMMARY;
CREATE TABLE SITE_LOG_SUMMARY
(  COL_LOG_ID       NUMBER
 , COL_VISIT_DATE   DATE
 , COL_CATEGORY     VARCHAR2(30)
 , COL_TOTAL_VISITS NUMBER);       

DROP   SEQUENCE SEQ_COL_LOG_ID;
CREATE SEQUENCE SEQ_COL_LOG_ID;


INSERT INTO SITE_LOG_SUMMARY
  (  COL_LOG_ID, COL_VISIT_DATE, COL_CATEGORY, COL_TOTAL_VISITS)
VALUES 
  (  SEQ_COL_LOG_ID.NEXTVAL, '01-JAN-16', 'NEW', 208);

INSERT INTO SITE_LOG_SUMMARY
  (  COL_LOG_ID, COL_VISIT_DATE, COL_CATEGORY, COL_TOTAL_VISITS)
VALUES 
  (  SEQ_COL_LOG_ID.NEXTVAL, '02-JAN-16', 'NEW', 502);

INSERT INTO SITE_LOG_SUMMARY
  (  COL_LOG_ID, COL_VISIT_DATE, COL_CATEGORY, COL_TOTAL_VISITS)
VALUES 
  (  SEQ_COL_LOG_ID.NEXTVAL, '03-JAN-16', 'NEW', 290);

INSERT INTO SITE_LOG_SUMMARY
  (  COL_LOG_ID, COL_VISIT_DATE, COL_CATEGORY, COL_TOTAL_VISITS)
VALUES 
  (  SEQ_COL_LOG_ID.NEXTVAL, '04-JAN-16', 'NEW', 288);

INSERT INTO SITE_LOG_SUMMARY
  (  COL_LOG_ID, COL_VISIT_DATE, COL_CATEGORY, COL_TOTAL_VISITS)
VALUES 
  (  SEQ_COL_LOG_ID.NEXTVAL, '05-JAN-16', 'NEW', 321);

INSERT INTO SITE_LOG_SUMMARY
  (  COL_LOG_ID, COL_VISIT_DATE, COL_CATEGORY, COL_TOTAL_VISITS)
VALUES 
  (  SEQ_COL_LOG_ID.NEXTVAL, '06-JAN-16', 'NEW', 401);

INSERT INTO SITE_LOG_SUMMARY
  (  COL_LOG_ID, COL_VISIT_DATE, COL_CATEGORY, COL_TOTAL_VISITS)
VALUES 
  (  SEQ_COL_LOG_ID.NEXTVAL, '07-JAN-16', 'NEW', 576);

INSERT INTO SITE_LOG_SUMMARY
  (  COL_LOG_ID, COL_VISIT_DATE, COL_CATEGORY, COL_TOTAL_VISITS)
VALUES 
  (  SEQ_COL_LOG_ID.NEXTVAL, '08-JAN-16', 'NEW', 801);

INSERT INTO SITE_LOG_SUMMARY
  (  COL_LOG_ID, COL_VISIT_DATE, COL_CATEGORY, COL_TOTAL_VISITS)
VALUES 
  (  SEQ_COL_LOG_ID.NEXTVAL, '09-JAN-16', 'NEW', 409);

INSERT INTO SITE_LOG_SUMMARY
  (  COL_LOG_ID, COL_VISIT_DATE, COL_CATEGORY, COL_TOTAL_VISITS)
VALUES 
  (  SEQ_COL_LOG_ID.NEXTVAL, '10-JAN-16', 'NEW', 991);

INSERT INTO SITE_LOG_SUMMARY
  (  COL_LOG_ID, COL_VISIT_DATE, COL_CATEGORY, COL_TOTAL_VISITS)
VALUES 
  (  SEQ_COL_LOG_ID.NEXTVAL, '11-JAN-16', 'NEW', 312);

INSERT INTO SITE_LOG_SUMMARY
  (  COL_LOG_ID, COL_VISIT_DATE, COL_CATEGORY, COL_TOTAL_VISITS)
VALUES 
  (  SEQ_COL_LOG_ID.NEXTVAL, '12-JAN-16', 'NEW', 389);

INSERT INTO SITE_LOG_SUMMARY
  (  COL_LOG_ID, COL_VISIT_DATE, COL_CATEGORY, COL_TOTAL_VISITS)
VALUES 
  (  SEQ_COL_LOG_ID.NEXTVAL, '01-JAN-16', 'RETURNING', 375);

INSERT INTO SITE_LOG_SUMMARY
  (  COL_LOG_ID, COL_VISIT_DATE, COL_CATEGORY, COL_TOTAL_VISITS)
VALUES 
  (  SEQ_COL_LOG_ID.NEXTVAL, '02-JAN-16', 'RETURNING', 390);

INSERT INTO SITE_LOG_SUMMARY
  (  COL_LOG_ID, COL_VISIT_DATE, COL_CATEGORY, COL_TOTAL_VISITS)
VALUES 
  (  SEQ_COL_LOG_ID.NEXTVAL, '03-JAN-16', 'RETURNING', 382);

INSERT INTO SITE_LOG_SUMMARY
  (  COL_LOG_ID, COL_VISIT_DATE, COL_CATEGORY, COL_TOTAL_VISITS)
VALUES 
  (  SEQ_COL_LOG_ID.NEXTVAL, '04-JAN-16', 'RETURNING', 420);

INSERT INTO SITE_LOG_SUMMARY
  (  COL_LOG_ID, COL_VISIT_DATE, COL_CATEGORY, COL_TOTAL_VISITS)
VALUES 
  (  SEQ_COL_LOG_ID.NEXTVAL, '05-JAN-16', 'RETURNING', 517);

INSERT INTO SITE_LOG_SUMMARY
  (  COL_LOG_ID, COL_VISIT_DATE, COL_CATEGORY, COL_TOTAL_VISITS)
VALUES 
  (  SEQ_COL_LOG_ID.NEXTVAL, '06-JAN-16', 'RETURNING', 702);

INSERT INTO SITE_LOG_SUMMARY
  (  COL_LOG_ID, COL_VISIT_DATE, COL_CATEGORY, COL_TOTAL_VISITS)
VALUES 
  (  SEQ_COL_LOG_ID.NEXTVAL, '07-JAN-16', 'RETURNING', 469);

INSERT INTO SITE_LOG_SUMMARY
  (  COL_LOG_ID, COL_VISIT_DATE, COL_CATEGORY, COL_TOTAL_VISITS)
VALUES 
  (  SEQ_COL_LOG_ID.NEXTVAL, '08-JAN-16', 'RETURNING', 487);

INSERT INTO SITE_LOG_SUMMARY
  (  COL_LOG_ID, COL_VISIT_DATE, COL_CATEGORY, COL_TOTAL_VISITS)
VALUES 
  (  SEQ_COL_LOG_ID.NEXTVAL, '09-JAN-16', 'RETURNING', 972);

INSERT INTO SITE_LOG_SUMMARY
  (  COL_LOG_ID, COL_VISIT_DATE, COL_CATEGORY, COL_TOTAL_VISITS)
VALUES 
  (  SEQ_COL_LOG_ID.NEXTVAL, '10-JAN-16', 'RETURNING', 860);

INSERT INTO SITE_LOG_SUMMARY
  (  COL_LOG_ID, COL_VISIT_DATE, COL_CATEGORY, COL_TOTAL_VISITS)
VALUES 
  (  SEQ_COL_LOG_ID.NEXTVAL, '11-JAN-16', 'RETURNING', 971);

INSERT INTO SITE_LOG_SUMMARY
  (  COL_LOG_ID, COL_VISIT_DATE, COL_CATEGORY, COL_TOTAL_VISITS)
VALUES 
  (  SEQ_COL_LOG_ID.NEXTVAL, '12-JAN-16', 'RETURNING', 450);

COMMIT;

REM
REM You are ready to begin.
REM 
